services:
    database:
        image: mysql:latest
        expose:
            - 3306
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD="nikos2002"
            - MYSQL_DATABASE="SpringBootDB"
    backend:
        image: distributed_systems_backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "7979:7979"
        depends_on:
            - database
