services:
    database:
        image: mysql:latest
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            interval: 20s
            retries: 5
        network_mode: "host"
    backend:
        image: distributed_systems_backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        expose:
            - 7979
        depends_on:
            database:
                condition: service_healthy
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:7979/actuator/health"]
            timeout: 20s
            interval: 20s
            retries: 5
        network_mode: "host"
    frontend:
        image: distributed_systems_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        expose:
            - 3000
        depends_on:
            backend:
                condition: service_healthy
        network_mode: "host"

