services:
    database:
        image: mysql:latest
        expose:
            - 3306
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: nikos2002
            MYSQL_DATABASE: SpringBootDB
        network_mode: "host"
    backend:
        image: distributed_systems_backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "7979:7979"
        depends_on:
            - database
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/SpringBootDB
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: "nikos2002"
        network_mode: "host"

